### ISSUE TITLE
Plans for TPAC

### ISSUE THREAD

**Issue by nrooney** [w3c/wg-effectiveness#27]
What would we like to do at TPAC? Here is a suggested list:

- Testing breakout session
- Testing plenary item (mostly for promotion)
- Guide & Github breakout sessiom
- WGE plenary item (to discuss all output)
- AC session (for those reps who didn't wake up for the plenary!)

**Comment by nrooney** [comment]
TPAC is coming up - so drop any thoughts you have on what we should be doing at TPAC here!

**Comment by nrooney** [comment]
I am currently thinking of a presentation which may feature some mantra like statements to get people to understand some of the more culture-based elements which are harder to change. Things such as "No Test No Merge" and "Shipping is a Feature". That maybe after-two-glasses-of-wine Natasha talking though.

**Comment by nrooney** [comment]
Meet with accessibility crew at TPAC to discuss on good github guides for accessibility

**Comment by jeffjaffe** [comment]
All great ideas.

Testing breakout session - MUST DO!!

Testing plenary item - That is already planned.

Guide and Github breakout session - Makes sense.

WGE plenary item:  I think it is a bit premature because I think we need to be further along for this very short plenary.
AC Session:  Hopefully Natasha knows that she is on the agenda!

**Comment by plehegar** [comment]
Testing breakout session: we have at least two so far:
 https://www.w3.org/wiki/TPAC/2017/SessionIdeas#web-platform-tests (general)
 https://www.w3.org/wiki/TPAC/2017/SessionIdeas#Cross-browser_interoperability_testing (KITE/WebRTC)
