### ISSUE TITLE
Cycling working methods?!

### ISSUE THREAD

**Issue by nrooney** [w3c/wg-effectiveness#67]
The W3C has often been very deadline driven with documents needing to be complete and almost "perfect" to be done and to have met the deadline.

Should we be encouraging more cyclic work? This could involve snapshots, shorter deadlines for incremental work, natural evolutions of documents over time.

Thoughts?

**Comment by nigelmegitt** [comment]
This is about driving behaviour in WGs - requiring tests before adding features, and having a GitHub pull request driven working mode, where approved pull requests get merged into the ED, and then saying "on some predefined date, we're going to push this into the next version, so get yourselves ready" would be really helpful. The tests help drive implementation alignment, the pull request review mechanism means that nobody in the group can say "I didn't have a chance to review that", and the jump to PR from CR is easier because you already have tests.

Of course the one variable the WG needs to be in control of (perhaps at Charter time) is how frequently the spec gets moved forward.

**Comment by nrooney** [comment]
We can add some of these into guidelines into /guide and I believe that adding testing to the process doc can assist with the other suggestions; but I'm not sure what else we can do to help here. I completely agree with @nigelmegitt's description of a great WG flow; I'm just trying to work out the best route to encourage and support WGs into doing it!

**Comment by nrooney** [comment]
evergreen standards, testing in process CG. These have been done.

Guidelines for chairs could be our contribution. Tink has some good ideas

**Comment by nrooney** [comment]
Closing - please reopen if you feel otherwise. AB evergreen standards work continues within AB.
