### ISSUE TITLE
is limiting continuous incubation prohibiting organic growth?

### ISSUE THREAD

**Issue by TzviyaSiegman** [w3c/wg-effectiveness#77]
The [Continuous Incubation](https://github.com/w3c/wg-effectiveness/blob/master/continuous_incubation.md) document describes a scenario of fresh ideas changing the course of a WG. This can be problematic, but it can also demonstrate that a group has adapted its needs organically. A healthy WG will work on real implementations as it develops and may need to change course. I am wary of being overly prescriptive about growth and incubation. Most of this should be covered by staying within the charter.

**Comment by jeffjaffe** [comment]
@TzviyaSiegman you are correct, but all extremes are bad.  The CI guidance came out of a review of WebRTC whose work has stretched out over 7 years.

**Comment by nrooney** [comment]
Adding incubation to charters would be a good thing (stated in meeting 14), suggest to process cg?

**Comment by murata2makoto** [comment]
I see a disadvantage in continuous incubation.  Suppose that you think of some idea and you want to sell it to the committee.  Other ideas from other people are also on the table.  Then, the conclusion is likely to add most of the ideas to the specification.   The result is a gigantic specification.  That's why W3C XML Schema became so huge.

**Comment by nrooney** [comment]
closing issue - will discuss in AC
